### ISSUE TITLE
How to set Username?

### ISSUE THREAD

**Issue by SolomonRosemite** [ckotzbauer/n26-api#105]
Hi,

This might sound kinda silly, but I'm not sure what I'm supposed to set for the Username.
As far as I know, when I log in to my n26 account. I need my email and password. A Username was never mentioned.

I have already tried using my email as username. But that failed.
Any advice where I can find my Username?

**Comment by ckotzbauer** [comment]
Hi,
the username is indeed the mail-address you use for login in the app or the webportal.

**Comment by SolomonRosemite** [comment]
I see. Unfortunately, I still receive the status code 401. I tried logging in using the web portal and that seem to have worked.
Any idea why this might be happening?
