### ISSUE TITLE
How legal is it?

### ISSUE THREAD

**Issue by skvav** [ckotzbauer/n26-api#12]
Hi! I would like to use your library in production for scraping data with the agreement of a bank client. But as far as I know PSD2 law explicitly prohibits screen scraping https://ec.europa.eu/commission/presscorner/detail/en/MEMO_17_4961. At the same time it says
> PSD2 prohibits TPPs from accessing any other data from the customer payment account beyond those explicitly authorised by the customer. Customers will have to agree on the access, use and processing of these data

That's why I'm quite confused. It seems that if you have an agreement you may use it. Maybe you had an experience of using your library in production and could shed some light on legal aspects.

**Comment by ckotzbauer** [comment]
Hi,
from technical perspective, this is not a screen-scraper in my opinion, as it uses the official REST-API from N26.

I use this library only for my personal needs, so no production-setup (for other customers as well) yet. But I'm not totally sure about how this library and its usage is affected by the PSD2 rules...
